package network.messages.userstate;

import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

import game.utility.ISendable;

public abstract class GameConfirmationRequestMessage
        extends AutoGeneratedTcpMessage<GameConfirmationRequestMessage.GameConfirmationRequest> {
    public static final byte id = 11;

    public final static record GameConfirmationRequest() implements ISendable {
    }
}
