package network.messages.userstate;

import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class GameConfirmationMessage extends AutoGeneratedTcpMessage<GameConfirmation> {
    public static final byte id = 6;
}
