package network.messages.userstate;

import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;
import utils.ISendable;

public abstract class GameConfirmationRequestMessage
        extends AutoGeneratedTcpMessage<GameConfirmationRequestMessage.Payload> {
    public static final byte id = 11;

    public final static record Payload() implements ISendable {
    }
}
