package network.messages.userstate;

// import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedUdpMessage;

// public abstract class GameConfirmationMessage extends AutoGeneratedTcpMessage<GameConfirmation> {
// NOTE: Sending this over udp to ensure that the player connection is stable when he declares being ready for gameplay
public abstract class GameConfirmationMessage extends AutoGeneratedUdpMessage<GameConfirmation> {
    public static final byte id = 6;
}
