subprojects {
    apply plugin: "java"

    java {
      sourceCompatibility = JavaVersion.VERSION_21
    }

    repositories {
        mavenLocal()
        mavenCentral()
    }

    ext {
      // gdxVersion = '1.13.1'
      gdxVersion = '1.12.1'
    }

    dependencies {
        // implementation project("core")

        testImplementation 'org.junit.jupiter:junit-jupiter:5.12.1'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
        // implementation platform('org.apache.logging.log4j:log4j-bom:2.24.3')
    }

    test {
        useJUnitPlatform()
        testLogging {
            events "passed", "skipped", "failed"
        }
    }
}
