package messagetraits;

import java.util.HashMap;
import java.util.Map;

import java.util.function.Function;

public class AutoGeneratedMessagesData {
    public static final Map<Class<?>, Object> recordDecoders = new HashMap<>();
    public static final Map<Byte, Object> decoders = new HashMap<>();

    @SuppressWarnings("unchecked")
    public static <U, T> Map<Class<?>, Function<U, T>> getRecordDecoders() {
        Map<Class<?>, Function<U, T>> casted = new HashMap<>();
        recordDecoders.forEach((key, value) -> casted.put(key, (Function<U, T>) value));
        return casted;
    }

    @SuppressWarnings("unchecked")
    public static <U, T> Map<Byte, Function<U, T>> getDecoders() {
        Map<Byte, Function<U, T>> casted = new HashMap<>();
        decoders.forEach((key, value) -> casted.put(key, (Function<U, T>) value));
        return casted;
    }
}
