package messagetraits;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import static javax.lang.model.element.ElementKind.*;
import static javax.lang.model.element.Modifier.*;
import com.google.auto.service.AutoService;

import codegen.AutoMessagesGenerator;
import codegen.MessageGeneratorFactory;
import utils.AnnotationState;
import utils.QualifiedNameGetter;

// import javax.tools.Diagnostic;

@SupportedSourceVersion(SourceVersion.RELEASE_21)
@SupportedAnnotationTypes({ "messagetraits.MessageTraits", "messagetraits.AutoMessageTraits",
        "messagetraits.AutoGeneratedMessage" })
@AutoService(Processor.class)
public class MessageTraitsChecker extends AbstractProcessor {
    private String errorPrefix = "Class %s is ill-formed: %s";
    private String notFinalNotClassErrMsg = "A subclass of Message should be final";
    private String invalidIdErrorMsg = """
            A concrete class implementing Message should have a public static final byte field with the name id and default value,
            """;
    private String idsShouldBeUniqueMsg = "id field should have unique values among different classes inheriting after Message";

    private String onlyOneClassAnnotatedWithAutoMessageTraits = "There should be only one class annotated with AutoMessageTraits";

    private String autoMessageShouldntBeFinal = "Auto generated message should be abstract";

    private final void errorMsg(Object el, String msg) {
        processingEnv.getMessager().printError(errorPrefix.formatted(el, msg));
    }

    private final Map<Byte, Object> ids = new HashMap<>();

    private final QualifiedNameGetter qualifiedNameGetter = new QualifiedNameGetter();

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment env) {
        // var temp = env.getElementsAnnotatedWith(AutoMessageTraits.class);
        // var firstEl = temp.iterator().next();
        // var mirrors = firstEl.getAnnotationMirrors();

        // processingEnv.getMessager().printNote("%s %s".formatted(annotations,
        // mirrors));

        // processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
        // "%s %s %s".formatted(String.valueOf(temp),
        // annotations, temp.stream().map(el -> el.getAnnotationMirrors()).toArray()));

        AutoMessagesGenerator generator = new MessageGeneratorFactory()
                .getMessageGenerator();

        if (generator == null) {
            errorMsg(env.getElementsAnnotatedWith(AutoMessageTraits.class),
                    onlyOneClassAnnotatedWithAutoMessageTraits);
            return true;
        }

        for (Element element : env.getElementsAnnotatedWith(MessageTraits.class)) {
            // %s".formatted(element));

            // TODO: auto generated classes should be abstract
            if (element.getKind() == INTERFACE) {
                continue;
            }

            if (element.getAnnotation(AutoGeneratedMessage.class) != null) {
                // processingEnv.getMessager().printNote("Found auto generated message:
                // %s".formatted(element));
                continue;
            }

            // processingEnv.getMessager().printNote("I am here %s %s".formatted(element,
            // String.valueOf(
            // AnnotationState.getAnnotationState(element, AutoMessageTraits.class, env))));
            //
            if (AnnotationState.getAnnotationState(element, AutoMessageTraits.class,
                    env) != AnnotationState.INHERITED) {
                if (element.getModifiers().contains(ABSTRACT)) {
                    continue;
                }

                if (!element.getModifiers()
                        .containsAll(List.of(FINAL))) {
                    errorMsg(element, notFinalNotClassErrMsg);
                    continue;
                }

            } else {

                if (!element.getModifiers()
                        .containsAll(List.of(ABSTRACT))) {
                    errorMsg(element, autoMessageShouldntBeFinal);
                    continue;
                }
            }

            if (element.getKind() != CLASS) {
                errorMsg(element, notFinalNotClassErrMsg);
            }

            var id = element.getEnclosedElements()
                    .stream()
                    .filter(el -> el.getSimpleName().toString().equals("id"))
                    .findFirst();

            if (!id.isPresent()) {
                errorMsg(element, invalidIdErrorMsg);
                continue;
            }

            Object idVal;
            if (id.get() instanceof VariableElement idVar
                    && idVar.getModifiers().containsAll(List.of(PUBLIC, STATIC, FINAL))
                    && (idVal = idVar.getConstantValue()) != null
                    && idVal instanceof Byte byteIdVal) {

                if (ids.containsKey(byteIdVal)) {
                    errorMsg(element, idsShouldBeUniqueMsg);
                } else {
                    ids.put(byteIdVal, byteIdVal);
                }
            } else {
                errorMsg(element, invalidIdErrorMsg);
            }

            if (element.getAnnotation(AutoMessageTraits.class) != null) {
                try {
                    var consumerProducer = qualifiedNameGetter.getConsumerProducer(processingEnv, element,
                            AutoMessageTraits.class);

                    if (consumerProducer == null) {
                        throw new IllegalStateException();
                    }

                    var messageTraitsQName = qualifiedNameGetter.getMessageTraitsQName(env);

                    generator.genClass(
                            consumerProducer, messageTraitsQName, (TypeElement) element, processingEnv);

                } catch (Exception e) {
                    errorMsg(element,
                            "Illegal state encountered while retreiving consumer and producer: %s %s".formatted(e,
                                    e.getMessage()));
                }
            }
        }

        return true;
    }
}
