package messagetraits;

import static javax.lang.model.element.ElementKind.CLASS;
import static javax.lang.model.element.ElementKind.INTERFACE;
import static javax.lang.model.element.Modifier.ABSTRACT;
import static javax.lang.model.element.Modifier.FINAL;
import static javax.lang.model.element.Modifier.PUBLIC;
import static javax.lang.model.element.Modifier.STATIC;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.TypeMirror;

import com.google.auto.service.AutoService;

import codegen.AutoGeneratedClassData;
import codegen.AutoMessagesGenerator;
import codegen.LoaderWriter;
import codegen.MessageGeneratorFactory;
import utils.AnnotationState;
import utils.GenericTypeUtils;
import utils.QualifiedNameGetter;

// import javax.tools.Diagnostic;

@SupportedSourceVersion(SourceVersion.RELEASE_21)
@SupportedAnnotationTypes({ "messagetraits.MessageTraits", "messagetraits.AutoMessageTraits",
        "messagetraits.AutoGeneratedMessage" })
@AutoService(Processor.class)
public class MessageTraitsChecker extends AbstractProcessor {
    private String errorPrefix = "Class %s is ill-formed: %s";
    private String notFinalNotClassErrMsg = "A subclass of Message should be final";
    private String invalidIdErrorMsg = """
            A concrete class implementing Message should have a public static final byte field with the name id and default value,
            """;
    private String idsShouldBeUniqueMsg = "id field should have unique values among different classes inheriting after Message";

    private String onlyOneClassAnnotatedWithAutoMessageTraits = "There should be only one class annotated with AutoMessageTraits";

    private String autoMessageShouldntBeFinal = "Auto generated message should be abstract";

    private final void errorMsg(Object el, String msg) {
        processingEnv.getMessager().printError(errorPrefix.formatted(el, msg));
    }

    private final void errorMsg(Object el, Exception e) {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        e.printStackTrace(pw);

        processingEnv.getMessager().printError(errorPrefix.formatted(el, sw.toString()));
    }

    private final Map<Byte, Object> ids = new HashMap<>();

    private final QualifiedNameGetter qualifiedNameGetter = new QualifiedNameGetter();

    private final LoaderWriter loaderWriter = new LoaderWriter();

    private String autoGeneratedBaseClassPackageName = null;

    private String producerQName = null;

    private TypeMirror messageTypeMirror;

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment env) {
        final Collection<AutoGeneratedClassData> autoGeneratedClassesData = new ArrayList<>();
        // processingEnv.getMessager()
        // .printNote("%s, %s".formatted(annotations.toString(),
        // String.valueOf(annotations.isEmpty())));

        AutoMessagesGenerator generator = new MessageGeneratorFactory()
                .getMessageGenerator();

        if (generator == null) {
            errorMsg(env.getElementsAnnotatedWith(AutoMessageTraits.class),
                    onlyOneClassAnnotatedWithAutoMessageTraits);
            return true;
        }

        for (Element element : env.getElementsAnnotatedWith(MessageTraits.class)) {
            if (element.getKind() == INTERFACE) {
                continue;
            }

            if (element.getAnnotation(AutoGeneratedMessage.class) != null) {
                continue;
            }

            if (AnnotationState.getAnnotationState(element, MessageTraits.class,
                    env) == AnnotationState.DIRECTLY_ANNOTATED) {
                messageTypeMirror = element.asType();
            }

            var state = AnnotationState.getAnnotationState(element, AutoMessageTraits.class,
                    env);

            if (state != AnnotationState.INHERITED) {
                if (element.getModifiers().contains(ABSTRACT)) {
                    // var consumerProducer = qualifiedNameGetter.getConsumerProducer(processingEnv,
                    // element,
                    // AutoMessageTraits.class);

                    if (state == AnnotationState.DIRECTLY_ANNOTATED) {
                        // processingEnv.getMessager()
                        // .printNote("Class %s is ill-formed: %s".formatted(element,
                        // "AutoMessageTraits should be inherited"));
                        autoGeneratedBaseClassPackageName = processingEnv.getElementUtils().getPackageOf(element)
                                .getQualifiedName().toString();
                    }

                    continue;
                }

                if (!element.getModifiers()
                        .containsAll(List.of(FINAL))) {
                    errorMsg(element, notFinalNotClassErrMsg);
                    continue;
                }

            } else {

                if (!element.getModifiers()
                        .containsAll(List.of(ABSTRACT))) {
                    errorMsg(element, autoMessageShouldntBeFinal);
                    continue;
                }
            }

            if (element.getKind() != CLASS) {
                errorMsg(element, notFinalNotClassErrMsg);
            }

            var id = element.getEnclosedElements()
                    .stream()
                    .filter(el -> el.getSimpleName().toString().equals("id"))
                    .findFirst();

            if (!id.isPresent()) {
                errorMsg(element, invalidIdErrorMsg);
                continue;
            }

            Object idVal;
            Byte idValAsByte = null;
            if (id.get() instanceof VariableElement idVar
                    && idVar.getModifiers().containsAll(List.of(PUBLIC, STATIC, FINAL))
                    && (idVal = idVar.getConstantValue()) != null
                    && idVal instanceof Byte byteIdVal) {

                idValAsByte = byteIdVal;

                if (ids.containsKey(byteIdVal)) {
                    errorMsg(element, idsShouldBeUniqueMsg);
                } else {
                    ids.put(byteIdVal, byteIdVal);
                }
            } else {
                errorMsg(element, invalidIdErrorMsg);
            }

            if (element.getAnnotation(AutoMessageTraits.class) != null) {
                try {
                    var consumerProducer = qualifiedNameGetter.getConsumerProducer(processingEnv, element,
                            AutoMessageTraits.class);

                    if (consumerProducer == null) {
                        throw new IllegalStateException();
                    }
                    producerQName = consumerProducer.producerQualifiedName();

                    var messageTraitsQName = qualifiedNameGetter.getMessageTraitsQName(env);

                    var generatedMessageQName = generator.genClass(
                            consumerProducer, messageTraitsQName, (TypeElement) element, processingEnv);

                    assert idValAsByte != null;

                    autoGeneratedClassesData.add(new AutoGeneratedClassData(generatedMessageQName,
                            GenericTypeUtils.getTemplateArgTypeMirror((TypeElement) element)));
                    // processingEnv.getMessager().printNote(generatedMessageQName);
                } catch (Exception e) {
                    // errorMsg(element,
                    // "Illegal state encountered while retreiving consumer and producer: %s
                    // %s".formatted(
                    // e,
                    // // e,
                    // e.getMessage()));
                    errorMsg(element, e);
                }
            }

        }

        if (!autoGeneratedClassesData.isEmpty()) {
            // if (annotations.isEmpty()) {
            try {
                if (autoGeneratedBaseClassPackageName == null) {
                    throw new IllegalStateException("No class is annotated with AutoMessageTraits");
                }

                // processingEnv.getMessager()
                // .printNote("Generating classes in
                // %s".formatted(autoGeneratedBaseClassPackageName));
                loaderWriter.loadWriter(autoGeneratedClassesData, processingEnv,
                        autoGeneratedBaseClassPackageName, messageTypeMirror, producerQName);
            } catch (Exception e) {
                processingEnv.getMessager().printError(
                        "Illegal state encountered while generating classes: %s ".formatted(e));
            }
        }

        return true;
    }
}
