package network.messages.loginstate;

import network.messages.Sendable;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedEncryptedMessage;

public abstract class PortInfoResponse extends AutoGeneratedEncryptedMessage<PortInfoResponse.Payload> {
    public static final byte id = 3;

    public static record Payload(int udpPort, int tcpPort) implements Sendable {

    }
}
