package network.messages.loginstate;

import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedEncryptedMessage;
import utils.ISendable;

public abstract class PortInfoRequest extends AutoGeneratedEncryptedMessage<PortInfoRequest.Payload> {
    public static final byte id = 2;

    public record Payload() implements ISendable {

    }
}
