package network.messages.loginstate;

import game.utility.ISendable;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedEncryptedMessage;

public abstract class PortInfoRequest extends AutoGeneratedEncryptedMessage<PortInfoRequest.Payload> {
    public static final byte id = 2;

    public record Payload() implements ISendable {

    }
}
