package network.messages.loginstate;

import network.messages.Sendable;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedEncryptedMessage;

public abstract class PortInfoRequest extends AutoGeneratedEncryptedMessage<PortInfoRequest.Payload> {
    public static final byte id = 2;

    public static record Payload() implements Sendable {

    }
}
