package network.messages.loginstate;

import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedEncryptedMessage;
import utils.ISendable;

public abstract class PortInfoResponse extends AutoGeneratedEncryptedMessage<PortInfoResponse.Payload> {
    public static final byte id = 3;

    public record Payload(int udpPort, int tcpPort) implements ISendable {

    }
}
