package network.messages.loginstate;

import game.utility.ISendable;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedEncryptedMessage;

public abstract class PortInfoResponse extends AutoGeneratedEncryptedMessage<PortInfoResponse.Payload> {
    public static final byte id = 3;

    public record Payload(int udpPort, int tcpPort) implements ISendable {

    }
}
