package network.messages.configurationstate;

import game.utility.ISendable;
import gameclient.rooms.RoomRequest;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;
// import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedUdpMessage;

public abstract class CreateRoomRequestResponse extends AutoGeneratedTcpMessage<CreateRoomRequestResponse.Payload> {
    // public abstract class CreateRoomRequestResponse extends
    // AutoGeneratedUdpMessage<CreateRoomRequestResponse.Payload> {
    public static final byte id = 10;

    public static record Payload(RoomRequest request, String roomName) implements ISendable {
    }
}
