package network.messages.configurationstate;

import gameclient.rooms.RoomConfig;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class CreateRoomRequest extends AutoGeneratedTcpMessage<RoomConfig> {
    // AutoGeneratedUdpMessage<CreateRoomRequest.Payload> {
    public static final byte id = 4;

}
