package network.messages.configurationstate;

import game.utility.ISendable;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class CreateRoomRequest extends AutoGeneratedTcpMessage<CreateRoomRequest.Payload> {
    // AutoGeneratedUdpMessage<CreateRoomRequest.Payload> {
    public static final byte id = 4;

    public record Payload(String name) implements ISendable {
    }
}
