package network.messages.configurationstate;

import network.messages.Sendable;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class CreateRoomRequest extends AutoGeneratedTcpMessage<CreateRoomRequest.Payload> {
    public static final byte id = 4;

    public static record Payload(String name) implements Sendable {
    }
}
