
package network.messages.configurationstate;

import matchmaking.MatchmakingParameters;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public class FindGameMessages {
    public static abstract class FindGameMessage extends AutoGeneratedTcpMessage<MatchmakingParameters> {
        public static final byte id = 20;
    }
}
