package network.messages.configurationstate;

import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;
import utils.ISendable;

public final class GameStartMessages {
    public static abstract class StartGameRequest extends AutoGeneratedTcpMessage<StartGameRequest.Payload> {
        // public abstract class CreateRoomRequestResponse extends
        // AutoGeneratedUdpMessage<CreateRoomRequestResponse.Payload> {
        public static final byte id = 12;

        public static record Payload() implements ISendable {
        }
    }

    public static abstract class GameStartedNotification
            extends AutoGeneratedTcpMessage<GameStartedNotification.Payload> {
        public static final byte id = 13;

        public static final record Payload() implements ISendable {
        }
    }

}
