package network.messages.configurationstate;

import gameclient.rooms.RoomConfig;
import gameclient.rooms.RoomInfo;
import gameclient.rooms.RoomRequestResult;
import gameclient.rooms.UserMembershipInfo;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;
import utils.ISendable;

public final class RoomMessages {
    public static abstract class CreateRoomRequest extends AutoGeneratedTcpMessage<RoomConfig> {
        public static final byte id = 4;
    }

    public static abstract class RoomMembershipMessage extends AutoGeneratedTcpMessage<UserMembershipInfo> {
        public static final byte id = 9;
    }

    public static abstract class RoomInfoMessage extends AutoGeneratedTcpMessage<RoomInfo> {
        public static final byte id = 8;
    }

    public static abstract class RoomRequestResponse
            extends AutoGeneratedTcpMessage<RoomRequestResult> {
        public static final byte id = 10;
    }

    public static abstract class JoinRoomRequest extends
            AutoGeneratedTcpMessage<JoinRoomRequest.Payload> {
        public static final byte id = 16;

        public static record Payload(String roomName, String password) implements ISendable {
        }
    }
}
