package network.messages.configurationstate;

import gameclient.rooms.RoomInfo;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class RoomInfoMessage extends AutoGeneratedTcpMessage<RoomInfo> {
    public static final byte id = 8;
}
