package network.messages.configurationstate;

import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;
import gameclient.rooms.UserMembershipInfo;

public abstract class RoomMembershipMessage extends AutoGeneratedTcpMessage<UserMembershipInfo> {
    public static final byte id = 9;
}
