package codegen;

import static codegen.CodegenConfig.DYNAMIC_SIZE;
import static codegen.CodegenConfig.idFieldName;
import static codegen.CodegenConfig.typeToTypeData;
import static com.palantir.javapoet.TypeName.BYTE;
import static javax.lang.model.element.ElementKind.RECORD;
import static javax.lang.model.element.Modifier.FINAL;
import static javax.lang.model.element.Modifier.PRIVATE;
import static javax.lang.model.element.Modifier.PUBLIC;
import static javax.lang.model.element.Modifier.STATIC;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;
import java.util.function.Function;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeMirror;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;

import messagetraits.AutoGeneratedMessage;
import utils.ConsumerProducer;

public class AutoMessagesGenerator {
    private final static ProducerGenerator producerGenerator = new ProducerGenerator();

    private byte getStaticSize(Iterable<FieldSpec> fieldSpecs) {
        byte staticSize = 0;

        for (FieldSpec field : fieldSpecs) {
            var mappedVal = CodegenConfig.typeToTypeData.get(field.type());
            if (mappedVal == null) {
                throw new IllegalStateException("Unsupported type: %s".formatted(field));
            }

            if (mappedVal.size() != DYNAMIC_SIZE) {
                staticSize += mappedVal.size();
            }
        }
        return staticSize;
    }

    private MethodSpec getGetAction(Iterable<FieldSpec> fieldSpecs, TypeMirror genericTypePar) {
        StringJoiner args = new StringJoiner(", ");
        List<Object> formatArgs = new ArrayList<>();
        formatArgs.add(genericTypePar);

        fieldSpecs.forEach(field -> {
            args.add("$N");
            formatArgs.add(field.name());
        });

        var methodBuilder = MethodSpec.methodBuilder(CodegenConfig.getActionMethodName)
                .addModifiers(PUBLIC, FINAL)
                .addAnnotation(Override.class)
                .returns(ClassName.get(genericTypePar));

        String format = "return new $T(" + args + ")";

        var codeBlock = CodeBlock.of(format, formatArgs.toArray());
        methodBuilder.addStatement(codeBlock);

        return methodBuilder.build();
    }

    private MethodSpec getEncodeAndWrite(Iterable<FieldSpec> fieldSpecs, String consumerQualifiedName) {
        var consumerParName = CodegenConfig.consumerParName;
        var consumerSpec = ParameterSpec.builder(ClassName.bestGuess(consumerQualifiedName), consumerParName)
                .build();
        var byteTypeNameData = typeToTypeData.get(BYTE);

        var methodBuilder = MethodSpec.methodBuilder(CodegenConfig.encodeAndWriteMethodName)
                .addModifiers(PUBLIC)
                .addException(IOException.class)
                .addAnnotation(Override.class)
                .addParameter(consumerSpec)
                .addStatement("$N.$L", consumerParName,
                        CodeBlock.of(byteTypeNameData.consumerMethod(), CodegenConfig.staticSizeFieldName))
                .addStatement("$N.$L", consumerParName,
                        CodeBlock.of(byteTypeNameData.consumerMethod(), CodegenConfig.idFieldName));

        fieldSpecs.forEach(field -> {
            var mappedVal = typeToTypeData.get(field.type());
            if (mappedVal == null) {
                throw new IllegalStateException("Unsupported type: %s".formatted(field));
            }

            methodBuilder.addStatement("$N.$L", consumerParName,
                    CodeBlock.of(mappedVal.consumerMethod(), field.name()).toString());
        });

        return methodBuilder.build();
    }

    private MethodSpec getConstructor(Iterable<FieldSpec> fieldSpecs) {
        var constructorBuilder = MethodSpec.constructorBuilder()
                .addModifiers(PUBLIC);

        fieldSpecs.forEach(field -> {
            constructorBuilder.addParameter(field.type(), field.name());
            constructorBuilder.addStatement("this.$N = $N", field.name(), field.name());
        });

        return constructorBuilder.build();
    }

    public void genClass(ConsumerProducer consumerProducer, String messageTraitsQualifiedName,
            TypeElement element, ProcessingEnvironment processingEnv) {
        String className = CodegenConfig.generatedClassNameFormat.formatted(element.getSimpleName());
        String packageName = processingEnv.getElementUtils()
                .getPackageOf(element).getQualifiedName().toString();

        var templateArgTypeMirror = getTemplateArgTypeMirror(element);

        var fieldSpecs = getFieldSpecs(templateArgTypeMirror, processingEnv);
        var constructor = getConstructor(fieldSpecs);
        var encodeAndWrite = getEncodeAndWrite(fieldSpecs, consumerProducer.consumerQualifiedName());

        var staticSize = getStaticSize(fieldSpecs);

        var staticSizeField = FieldSpec.builder(Byte.class, CodegenConfig.staticSizeFieldName, PRIVATE, STATIC, FINAL)
                .initializer(CodeBlock.of("$L", staticSize)).build();

        var getAction = getGetAction(fieldSpecs, templateArgTypeMirror);

        var produceMethod = producerGenerator.getProduceMethod(fieldSpecs, consumerProducer.producerQualifiedName(),
                element);

        var produceFromRecordMethod = producerGenerator.getProduceFromRecordMethod(fieldSpecs, templateArgTypeMirror,
                element);

        var autoGenDataCl = CodegenConfig.autoGeneratedDataClass;

        var addToStructures = CodeBlock.builder()
                .addStatement("$T<$T, ?> decoder = $L::$L", Function.class,
                        ClassName.bestGuess(consumerProducer.producerQualifiedName()), className,
                        CodegenConfig.decodeMethodName)
                .addStatement("$T<$T, ?> recordDecoder = $L::$L", Function.class,
                        Object.class, className,
                        CodegenConfig.decodeFromRecordMethodName)
                .addStatement("$T.$N.put($L, $N)", autoGenDataCl,
                        CodegenConfig.decodersMapName,
                        idFieldName, "decoder")
                .addStatement("$T.$N.put($T.class, $L)", autoGenDataCl,
                        CodegenConfig.recordDecodersMapName,
                        templateArgTypeMirror, "recordDecoder")
                .build();

        TypeSpec generatedClass = TypeSpec.classBuilder(className)
                .addAnnotation(AutoGeneratedMessage.class)
                .superclass(ClassName.bestGuess(element.getQualifiedName().toString())) // ← this is how you add
                                                                                        // 'extends'
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addField(staticSizeField)
                .addFields(fieldSpecs)
                .addMethod(constructor)
                .addMethod(produceMethod)
                .addMethod(produceFromRecordMethod)
                .addMethod(encodeAndWrite)
                .addMethod(getAction)
                .addStaticBlock(addToStructures)
                .build();

        JavaFile javaFile = JavaFile.builder(packageName, generatedClass)
                .build();

        try {
            javaFile.writeTo(processingEnv.getFiler());

        } catch (IOException e) {
            processingEnv.getMessager()
                    .printError("Error encountered while generating classes: %s".formatted(e.toString()));
        }
    }

    private final TypeMirror getTemplateArgTypeMirror(TypeElement element) {
        var superClass = (DeclaredType) element.getSuperclass();
        var typeArgs = superClass.getTypeArguments();

        if (typeArgs.size() != 1) {
            throw new IllegalStateException();
        }

        return typeArgs.getFirst();
    }

    private final TypeElement getGenericTypePar(TypeMirror typeMirror, ProcessingEnvironment processingEnvironment) {
        var typeUtils = processingEnvironment.getTypeUtils();
        var typeEl = (TypeElement) typeUtils.asElement(typeMirror);

        // processingEnvironment.getMessager().printNote("Record type:
        // %s".formatted(typeEl.toString()));
        return typeEl;
    }

    private final Iterable<FieldSpec> getFieldSpecs(TypeMirror typeMirror,
            ProcessingEnvironment processingEnvironment) {
        var typeEl = getGenericTypePar(typeMirror, processingEnvironment);

        if (typeEl.getKind() != RECORD) {
            processingEnvironment.getMessager().printError(
                    "Template argument: %s to AutoGeneratedMessage should be a record".formatted(typeEl));
            throw new IllegalStateException();
        }

        var recordFields = typeEl.getRecordComponents();

        return recordFields.stream().map(recordComponent -> FieldSpec.builder(TypeName.get(recordComponent.asType()),
                recordComponent.getSimpleName().toString(), PRIVATE, FINAL)
                .build()).toList();
    }
}
