package codegen;

import static codegen.CodegenConfig.MESSAGE_SIZE_TYPE;
import static codegen.CodegenConfig.answerVarName;
import static codegen.CodegenConfig.getDynamicSizeMethodName;
import static codegen.CodegenConfig.idFieldName;
import static codegen.CodegenConfig.tempSizeFieldName;
import static codegen.CodegenConfig.typeToTypeData;
import static com.palantir.javapoet.TypeName.BYTE;
import static javax.lang.model.element.Modifier.FINAL;
import static javax.lang.model.element.Modifier.PRIVATE;
import static javax.lang.model.element.Modifier.PUBLIC;
import static javax.lang.model.element.Modifier.STATIC;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;
import java.util.function.Predicate;
import java.util.stream.Stream;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.ElementFilter;
import javax.lang.model.util.Elements;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;

import messagetraits.AutoGeneratedMessage;
import utils.ConsumerProducer;
import utils.GenericTypeUtils;

// TODO: Add checking whether the template parameters are unique
public class AutoMessagesGenerator {
    private final static ProducerGenerator producerGenerator = new ProducerGenerator();

    private byte getStaticSize(ClassDetailsRec classDetails) {
        byte staticSize = CodegenConfig.MESSAGE_CODE_SIZE;

        // for (FieldSpec field : fieldSpecs) {
        // var mappedVal = getTypeNameData(field.type());
        //
        // if (mappedVal.size() != DYNAMIC_SIZE) {
        // staticSize += mappedVal.size();
        // }
        // }

        staticSize += classDetails.fieldsStaticSize();
        return staticSize;
    }

    private MethodSpec getGetSendable(Iterable<FieldSpec> fieldSpecs, TypeMirror genericTypePar) {
        StringJoiner args = new StringJoiner(", ");
        List<Object> formatArgs = new ArrayList<>();
        formatArgs.add(genericTypePar);

        fieldSpecs.forEach(field -> {
            args.add("$N");
            formatArgs.add(field.name());
        });

        var methodBuilder = MethodSpec.methodBuilder(CodegenConfig.getSendableMethodName)
                .addModifiers(PUBLIC, FINAL)
                .addAnnotation(Override.class)
                .returns(ClassName.get(genericTypePar));

        String format = "return new $T(" + args + ")";

        var codeBlock = CodeBlock.of(format, formatArgs.toArray());
        methodBuilder.addStatement(codeBlock);

        return methodBuilder.build();
    }

    private MethodSpec getGetDynamicSize(ClassDetailsRec classDetails) {
        var retType = MESSAGE_SIZE_TYPE;

        var methodBuilder = MethodSpec.methodBuilder(CodegenConfig.getDynamicSizeMethodName)
                .addModifiers(PRIVATE)
                .addModifiers(FINAL)
                .returns(retType);

        int initialDynamicSizeVal = classDetails.dynamicFieldsBaseSize();

        // var calculateDynamicSizeBlockBuilder = CodeBlock.builder();

        // for (FieldSpec field : fieldSpecs) {
        // var mappedVal = getTypeNameData(field.type());
        //
        // if (mappedVal.size() == DYNAMIC_SIZE) {
        // initialDynamicSizeVal += CodegenConfig.STRING_SIZE_VALUE_SIZE;
        //
        // calculateDynamicSizeBlockBuilder
        // .addStatement(mappedVal.updateDynamicSizeCodeblock().get().apply(field.name()));
        // }
        // }
        //
        methodBuilder.addStatement("$T $N = $L", retType, answerVarName, initialDynamicSizeVal);

        if (filterOutEmpty.test(classDetails.calculateDynamicSizeCodeBlock())) {
            methodBuilder.addCode("$N += $L;\n", answerVarName, classDetails.calculateDynamicSizeCodeBlock());
        }
        // .addStatement("return $N", classDetails.calculateDynamicSizeCodeBlock());
        methodBuilder.addStatement("return $N", answerVarName);

        return methodBuilder.build();
    }

    private static final Predicate<CodeBlock> filterOutEmpty = block -> !block.equals(CodeBlock.of(""));

    private ClassDetailsRec getClassDetailsRec(Element element, String elAsFieldName,
            ProcessingEnvironment processingEnvironment, TypeMirror isendableTypeMirror,
            TypeMirror fixedSizeArrayWrapperMirror) {
        return getClassDetailsRec(element, elAsFieldName, processingEnvironment, isendableTypeMirror,
                fixedSizeArrayWrapperMirror, 0);
    }

    private ClassDetailsRec getClassDetailsRec(Element element, String elAsFieldName,
            ProcessingEnvironment processingEnvironment, TypeMirror isendableTypeMirror,
            TypeMirror fixedSizeArrayWrapperMirror, int depth) {
        if (depth > CodegenConfig.maxDepth) {
            processingEnvironment.getMessager().printError("Maximum recursion depth exceeded");
        }

        var typeUtils = processingEnvironment.getTypeUtils();
        // processingEnvironment.getMessager().printNote("Entering %s
        // %s".formatted(element, elAsFieldName));

        if (typeUtils.isAssignable(element.asType(), isendableTypeMirror)) {
            assert typeUtils.asElement(element.asType()) instanceof TypeElement;
            var asTypeEl = (TypeElement) typeUtils.asElement(element.asType());

            var fields = asTypeEl.getRecordComponents();
            // var fields = ElementFilter.recordComponentsIn(element.getEnclosedElements());

            // processingEnvironment.getMessager().printNote("Fields in %s:
            // %s".formatted(element.asType(), fields));

            var reduced = fields.stream().map(
                    el -> getClassDetailsRec(el,
                            "%s.%s".formatted(elAsFieldName, el.getSimpleName().toString() + ((depth > 0) ? "()" : "")),
                            processingEnvironment,
                            isendableTypeMirror,
                            fixedSizeArrayWrapperMirror, depth + 1))
                    .reduce((prev, act) -> new ClassDetailsRec(
                            prev.fieldsStaticSize() + act.fieldsStaticSize(),
                            CodeBlock.join(List.of(prev.writeTheClass(), act.writeTheClass()), ";\n"),
                            prev.dynamicFieldsBaseSize() + act.dynamicFieldsBaseSize(),
                            CodeBlock.join(
                                    Stream.of(prev.calculateDynamicSizeCodeBlock(), act.calculateDynamicSizeCodeBlock())
                                            .filter(filterOutEmpty)
                                            .toList(),
                                    " + "),
                            CodeBlock.join(
                                    Stream.of(prev.loadTheClass(), act.loadTheClass())
                                            .filter(filterOutEmpty)
                                            .toList(),
                                    ", ")))
                    .orElse(new ClassDetailsRec());

            return new ClassDetailsRec(reduced.fieldsStaticSize(), reduced.writeTheClass(),
                    reduced.dynamicFieldsBaseSize(),
                    reduced.calculateDynamicSizeCodeBlock(),
                    CodeBlock.of("new $T($L)", element.asType(), reduced.loadTheClass()));
        }

        if (typeUtils.isSameType(typeUtils.erasure(element.asType()), typeUtils.erasure(fixedSizeArrayWrapperMirror))) {
            // var typeEl = GenericTypeUtils.typeElementOutOfTypeMirror(element.asType(),
            // processingEnvironment.getTypeUtils());

            var templateArgTypeMirror = GenericTypeUtils.getTemplateArgTypeMirror(element.asType(), typeUtils);

            // processingEnvironment.getMessager()
            // .printNote("TypeEl %s %s".formatted(templateArgTypeMirror,
            // element.asType()));

            // var templateArgTypeMirror =
            // GenericTypeUtils.getTemplateArgTypeMirror(typeEl);
            //
            assert (templateArgTypeMirror.getKind() == TypeKind.DECLARED);

            DeclaredType firstDeclared = (DeclaredType) templateArgTypeMirror;
            var el = firstDeclared.asElement();

            // TODO: add "arg" to CodegenConfig
            var classData = getClassDetailsRec(el, "arg", processingEnvironment,
                    isendableTypeMirror, fixedSizeArrayWrapperMirror, depth + 1);

            // processingEnvironment.getMessager().printNote("Recursed into this class data
            // %s".formatted(classData));

            CodeBlock supplierLambda = CodeBlock.builder()
                    .add("() -> ")
                    .beginControlFlow("")
                    .beginControlFlow("try")
                    .addStatement("return $L", classData.loadTheClass())
                    .nextControlFlow("catch ($T e)", IOException.class)
                    .addStatement("throw new $T(e)", IllegalStateException.class)
                    .endControlFlow() // end try/catch
                    .endControlFlow() // end lambda block
                    .build();

            var accumulatorBuilder = CodeBlock.builder();
            accumulatorBuilder.add("return size + $L", classData.fieldsStaticSize());
            if (filterOutEmpty.test(classData.calculateDynamicSizeCodeBlock())) {
                accumulatorBuilder.add(" + $L\n", classData.calculateDynamicSizeCodeBlock());
            }

            CodeBlock accumulateCodeBlock = CodeBlock.builder()
                    .add("$N.accumulate(0, (size, arg) -> ", elAsFieldName)
                    .beginControlFlow("")
                    .addStatement(accumulatorBuilder.build())
                    // .endControlFlow("")
                    .add("})")
                    .build();

            var forEachInsides = CodeBlock.builder()
                    // .addStatement()
                    .beginControlFlow("try")
                    .add("$L;\n", classData.writeTheClass())
                    .nextControlFlow("catch ($T e)", IOException.class)
                    .add("throw new $T(e);\n", IllegalStateException.class)
                    .endControlFlow()
                    .build();

            var forEachCodeBlock = CodeBlock.builder()
                    .add(CodegenConfig.getTypeNameData(TypeName.BYTE).consumerMethod().apply(elAsFieldName + ".size()"))
                    .add(";\n")
                    .add("$N.$N($L)", elAsFieldName, "forEach",
                            CodeBlock.builder()
                                    .add("arg -> ")
                                    .beginControlFlow("")
                                    .add(forEachInsides)
                                    .endControlFlow().build())
                    .build();

            // var forEachCodeBlock = CodeBlock.of("$N.forEach(arg -> {\n$L;\n})",
            // elAsFieldName, forEachInsides);

            var loadTheClassCodeBlock = CodeBlock.builder()
                    // .add(CodegenConfig.getTypeNameData(TypeName.BYTE).producerMethod()
                    // .apply(elAsFieldName + ".size()"))
                    // .add(";\n")
                    .add("$T.$N($L, $L, $T.class)",
                            typeUtils.erasure(fixedSizeArrayWrapperMirror),
                            CodegenConfig.getArrayFromSupplierMethodName,
                            CodegenConfig.getTypeNameData(TypeName.BYTE).producerMethod().apply(elAsFieldName),
                            supplierLambda,
                            templateArgTypeMirror)
                    // .add(";\n")
                    .build();

            return new ClassDetailsRec(
                    0,
                    forEachCodeBlock,
                    Byte.BYTES,
                    accumulateCodeBlock,
                    loadTheClassCodeBlock);
        }

        var mappedVal = CodegenConfig.getTypeNameData(TypeName.get(element.asType()));

        CodeBlock calcDynamicSize = mappedVal.updateDynamicSizeCodeblock().isEmpty() ? CodeBlock.of("")
                : mappedVal.updateDynamicSizeCodeblock().get().apply(elAsFieldName);

        return new ClassDetailsRec(
                Math.max(mappedVal.size(), 0),
                mappedVal.consumerMethod().apply(elAsFieldName),
                mappedVal.size() == CodegenConfig.DYNAMIC_SIZE ? Byte.BYTES : 0,
                // mappedVal.size() < 0 ? mappedVal.size() * -1 : 0,
                calcDynamicSize,
                mappedVal.producerMethod().apply(elAsFieldName));
    }

    private MethodSpec getEncodeAndWrite(String consumerQualifiedName,
            ClassDetailsRec classDetails) {

        var consumerParName = CodegenConfig.consumerParName;
        var consumerSpec = ParameterSpec.builder(ClassName.bestGuess(consumerQualifiedName), consumerParName)
                .addModifiers(FINAL)
                .build();
        var byteTypeNameData = typeToTypeData.get(BYTE);

        var calculateSizeCodeBlock = CodeBlock.of("($T)($N + $N())", MESSAGE_SIZE_TYPE,
                // classDetails.fieldsStaticSize + 1,
                CodegenConfig.staticSizeFieldName,
                getDynamicSizeMethodName);

        var methodBuilder = MethodSpec.methodBuilder(CodegenConfig.encodeAndWriteMethodName)
                .addModifiers(PUBLIC)
                .addException(IOException.class)
                .addAnnotation(Override.class)
                .addParameter(consumerSpec)
                .addStatement(CodeBlock.of("var $N = $L", tempSizeFieldName, calculateSizeCodeBlock))
                .addStatement(byteTypeNameData.consumerMethod().apply(tempSizeFieldName))
                .addStatement(byteTypeNameData.consumerMethod().apply(idFieldName))
                .addStatement(classDetails.writeTheClass());

        return methodBuilder.build();
    }

    private MethodSpec getConstructor(Iterable<FieldSpec> fieldSpecs) {
        var constructorBuilder = MethodSpec.constructorBuilder()
                .addModifiers(PUBLIC);

        fieldSpecs.forEach(field -> {
            constructorBuilder.addParameter(field.type(), field.name());
            constructorBuilder.addStatement("this.$N = $N", field.name(), field.name());
        });

        return constructorBuilder.build();
    }

    public String genClass(ConsumerProducer consumerProducer, String messageTraitsQualifiedName,
            TypeElement element, ProcessingEnvironment processingEnv) {
        var templateArgTypeMirror = GenericTypeUtils.getTemplateArgTypeMirror(element);
        Element argElement = processingEnv.getTypeUtils().asElement(templateArgTypeMirror);

        Elements elementUtils = processingEnv.getElementUtils();

        TypeElement iSendableTypeElement = elementUtils.getTypeElement(CodegenConfig.iSendableClassPath);
        TypeMirror isendableTypeMirror = iSendableTypeElement.asType();

        TypeElement fixedSizeArrayWrapperTypeEl = elementUtils.getTypeElement(CodegenConfig.fixedSizeArrayClassPath);
        TypeMirror fixedSizeArrayWrapperMirror = fixedSizeArrayWrapperTypeEl.asType();

        var classDetails = getClassDetailsRec(argElement, "this", processingEnv, isendableTypeMirror,
                fixedSizeArrayWrapperMirror);

        String className = CodegenConfig.generatedClassNameFormat.formatted(element.getSimpleName());
        String packageName = processingEnv.getElementUtils()
                .getPackageOf(element).getQualifiedName().toString();

        var fieldSpecs = GenericTypeUtils.getFieldSpecs(templateArgTypeMirror, processingEnv);
        var constructor = getConstructor(fieldSpecs);

        var encodeAndWrite = getEncodeAndWrite(consumerProducer.consumerQualifiedName(), classDetails);

        var getDynamicSize = getGetDynamicSize(classDetails);

        var staticSize = getStaticSize(classDetails);

        var staticSizeField = FieldSpec.builder(BYTE, CodegenConfig.staticSizeFieldName, PRIVATE, STATIC, FINAL)
                .initializer(CodeBlock.of("$L", staticSize)).build();

        // processingEnv.getMessager().printNote(classDetails.toString());

        var getSendable = getGetSendable(fieldSpecs, templateArgTypeMirror);

        // var produceMethod = producerGenerator.getProduceMethod(fieldSpecs,
        // consumerProducer.producerQualifiedName(),
        // element);

        var produceMethod = producerGenerator.getProduceMethod(classDetails,
                consumerProducer.producerQualifiedName(),
                element, processingEnv);

        var produceFromRecordMethod = producerGenerator.getProduceFromRecordMethod(fieldSpecs,
                templateArgTypeMirror,
                element);

        TypeSpec generatedClass = TypeSpec.classBuilder(className)
                .addAnnotation(AutoGeneratedMessage.class)
                .superclass(ClassName.bestGuess(element.getQualifiedName().toString())) // ← this is how you add
                // 'extends'
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addField(staticSizeField)
                .addFields(fieldSpecs)
                .addMethod(constructor)
                .addMethod(getDynamicSize)
                .addMethod(produceMethod)
                .addMethod(produceFromRecordMethod)
                .addMethod(encodeAndWrite)
                .addMethod(getSendable)
                .build();

        JavaFile javaFile = JavaFile.builder(packageName, generatedClass)
                .build();

        try {
            javaFile.writeTo(processingEnv.getFiler());

            return "%s.%s".formatted(packageName, className);
        } catch (IOException e) {
            processingEnv.getMessager()
                    .printError("Error encountered while generating classes: %s".formatted(e.toString()));
            throw new IllegalStateException(e);
        }
    }
}
