package codegen;

import java.io.IOException;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.lang.model.type.TypeMirror;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import com.palantir.javapoet.WildcardTypeName;

public class LoaderWriter {
    private final Iterable<FieldSpec> getStructuresFields(String producerQName, TypeMirror messageTypeMirror) {
        var decodersFuncType = ParameterizedTypeName.get(
                ClassName.get(Function.class),
                ClassName.bestGuess(producerQName),
                WildcardTypeName.subtypeOf(ClassName.get(messageTypeMirror)));

        var recordDecodersFuncType = ParameterizedTypeName.get(
                ClassName.get(Function.class),
                ClassName.get(Object.class),
                WildcardTypeName.subtypeOf(ClassName.get(messageTypeMirror)));

        FieldSpec decodersField = FieldSpec.builder(
                ParameterizedTypeName.get(
                        ClassName.get(Map.class),
                        ClassName.get(Byte.class),
                        decodersFuncType),
                CodegenConfig.decodersMapName,
                Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("new $T<>()", HashMap.class)
                .build();

        FieldSpec recordDecodersField = FieldSpec.builder(
                ParameterizedTypeName.get(
                        ClassName.get(Map.class),
                        ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)),
                        recordDecodersFuncType),
                CodegenConfig.recordDecodersMapName,
                Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("new $T<>()", ClassName.get(HashMap.class))
                .build();
        return List.of(decodersField, recordDecodersField);
    }

    private CodeBlock initStructuresBlock(Collection<AutoGeneratedClassData> generatedQualifiedNames) {

        var initDecodersBuilder = CodeBlock.builder();
        var initRecordDecodersBuilder = CodeBlock.builder();

        for (var clData : generatedQualifiedNames) {
            var clName = ClassName.bestGuess(clData.name());

            initRecordDecodersBuilder.addStatement("$L.put($T.class, $T::$L)",
                    CodegenConfig.recordDecodersMapName,
                    ClassName.get(clData.recordTypeMirror()),
                    clName,
                    CodegenConfig.decodeFromRecordMethodName);

            initDecodersBuilder.addStatement("$L.put($T.valueOf($T.$L), $T::$L)",
                    CodegenConfig.decodersMapName,
                    Byte.class,
                    clName,
                    CodegenConfig.idFieldName,
                    clName,
                    CodegenConfig.decodeMethodName);
        }

        return CodeBlock.builder()
                .add(initDecodersBuilder.build())
                .add(initRecordDecodersBuilder.build())
                .build();
    }

    public void loadWriter(Collection<AutoGeneratedClassData> generatedClassesData, ProcessingEnvironment processingEnv,
            String packageName, TypeMirror messageTypeMirror, String producerQName) {
        // var loadBlockBuilder = CodeBlock.builder()
        // .beginControlFlow("try");

        // for (var clData : generatedClassesData) {
        // loadBlockBuilder.addStatement("$T.forName(\"$N\")", Class.class,
        // clData.name());
        // }
        // loadBlockBuilder.nextControlFlow("catch ($T e)", Exception.class)
        // .addStatement("throw new $T($N)", IllegalStateException.class, "e")
        // .endControlFlow();
        //
        var mapsFields = getStructuresFields(producerQName, messageTypeMirror);

        var initBlock = initStructuresBlock(generatedClassesData);

        TypeSpec generatedClass = TypeSpec.classBuilder(CodegenConfig.generatedClassesLoaderName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addFields(mapsFields)
                // .addStaticBlock(loadBlockBuilder.build())
                .addStaticBlock(initBlock)
                .build();

        JavaFile javaFile = JavaFile.builder(packageName, generatedClass)
                .build();

        try {
            // processingEnv.getMessager()
            // .printNote("Generating class in %s.%s".formatted(packageName,
            // CodegenConfig.generatedClassesLoaderName));
            javaFile.writeTo(processingEnv.getFiler());

        } catch (IOException e) {
            processingEnv.getMessager()
                    .printError("Error encountered while generating classes: %s".formatted(e.toString()));
            throw new IllegalStateException(e);
        }
    }
}
