package network.messages.defaultmessage;

import java.util.Collections;
import java.util.Map;
import java.util.function.Function;

import messagetraits.AutoMessageTraits;
import network.messages.Message;
import network.messages.Message.EncryptedMessage;
import network.messages.Message.TCPMessage;
import network.messages.Message.UDPMessage;
import game.utility.ISendable;
import network.messages.utils.DataConsumer;
import network.messages.utils.DataProducer;

public final class AutoGeneratedMessages {
    public static Map<Byte, Function<DataProducer, ? extends Message>> decoders = Collections
            .unmodifiableMap(GeneratedClassesData.decoders);
    public static Map<Class<?>, Function<Object, ? extends Message>> recordDecoders = Collections
            .unmodifiableMap(GeneratedClassesData.recordDecoders);

    @AutoMessageTraits(consumer = DataConsumer.class, producer = DataProducer.class)
    public static abstract class AutoGeneratedEncryptedMessage<T extends ISendable> extends EncryptedMessage {
    }

    @AutoMessageTraits(consumer = DataConsumer.class, producer = DataProducer.class)
    public static abstract class AutoGeneratedUdpMessage<T extends ISendable> extends UDPMessage {
    }

    @AutoMessageTraits(consumer = DataConsumer.class, producer = DataProducer.class)
    public static abstract class AutoGeneratedTcpMessage<T extends ISendable> extends TCPMessage {
    }
}

// record PositionRecord(int i, byte b, int y) implements Sendable {
// };
//
// abstract class Position extends AutoGeneratedUdpMessage<PositionRecord> {
// public static final byte id = 20;
// }
