package network.messages.defaultmessage;

import java.util.Map;
import java.util.function.Function;

import messagetraits.AutoGeneratedMessagesData;
import network.messages.Message;

public class ConcreteObjectDecoder implements ObjectToMessageDecoder {
    private static final Map<Class<?>, Function<Object, Message>> recordDecoders = AutoGeneratedMessagesData
            .getRecordDecoders();

    @Override
    public Message decodeFromRecord(Object record) {
        return recordDecoders.get(record).apply(record);
    }
}
