package network.messages.defaultmessage;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
// import java.util.Objects;
import java.util.function.Function;

import network.messages.Message;
import utils.ISendable;

public class ConcreteObjectDecoder implements ObjectToMessageDecoder {
    private static final Map<Class<?>, Function<Object, ? extends Message>> recordDecoders = new HashMap<>();
    static {
        recordDecoders.putAll(AutoGeneratedMessages.recordDecoders);
    }

    @Override
    public Message decodeFromRecord(ISendable record) {
        return Objects.requireNonNull(recordDecoders.get(record.getClass()),
                "Unexpected object here %s".formatted(record)).apply(record);
        // return recordDecoders.get(record.getClass()).apply(record);
    }
}
