package network.messages.defaultmessage;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.logging.Logger;

import network.messages.Message;

public class ConcreteObjectDecoder implements ObjectToMessageDecoder {
    private static final Map<Class<?>, Function<Object, ? extends Message>> recordDecoders = new HashMap<>();
    static {
        recordDecoders.putAll(AutoGeneratedMessages.recordDecoders);
    }

    @Override
    public Message decodeFromRecord(Object record) {
        return recordDecoders.get(record.getClass()).apply(record);
    }
}
