package network.messages.gameplaystate;

import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;
import utils.ISendable;

public abstract class ExitTheGameMessage extends AutoGeneratedTcpMessage<ExitTheGameMessage.Payload> {
    public static final byte id = 22;

    public static record Payload() implements ISendable {
    }
}
