package network.messages.gameplaystate;

import game.gamestates.PlayerInventoryState;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class InventoryStateMessage extends
        AutoGeneratedTcpMessage<PlayerInventoryState> {
    public static final byte id = 18;
}
