package network.messages.gameplaystate;

import game.actions.PlayerMove;
// import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedUdpMessage;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class PlayerMoveMessage extends AutoGeneratedTcpMessage<PlayerMove> {
    public static final byte id = 5;

}
