package network.messages.gameplaystate;

import game.actions.PlayerSlotUse;
// import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedUdpMessage;
//
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class PlayerSlotUseMessage extends AutoGeneratedTcpMessage<PlayerSlotUse> {
    public static final byte id = 7;
}
