package network.messages.gameplaystate;

import game.gamestates.PlayerDeathState;
// import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedUdpMessage;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedTcpMessage;

public abstract class PlayerDeathMessage extends AutoGeneratedTcpMessage<PlayerDeathState> {
    public static final byte id = 21;
}
