package network.messages.gameplaystate;

import game.actions.PlayerSlotUse;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedUdpMessage;

public abstract class PlayerSlotUseMessage extends AutoGeneratedUdpMessage<PlayerSlotUse> {
    public static final byte id = 7;
}
