package network.messages.gameplaystate;

import game.actions.PlayerMove;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedUdpMessage;

public abstract class PlayerMoveMessage extends AutoGeneratedUdpMessage<PlayerMove> {
    public static final byte id = 5;

}
