package network.messages.gameplaystate;

import game.gamestates.*;
import network.messages.defaultmessage.AutoGeneratedMessages.AutoGeneratedUdpMessage;

class StatesMessages {
    public static abstract class PlayerStateMessage extends AutoGeneratedUdpMessage<PlayerState> {
        public static final byte id = 14;
    }

    public static abstract class EntityStateMessage extends AutoGeneratedUdpMessage<EntityState> {
        public static final byte id = 15;
    }

}
