package network.messages.gameplaystate;

import game.gamestates.EntityState;
import game.gamestates.PlayerState;
import network.messages.defaultmessage.AutoGeneratedMessages.*;

class StatesMessages {
    // public static abstract class PlayerStateMessage extends
    // AutoGeneratedUdpMessage<PlayerState> {
    public static abstract class PlayerStateMessage extends AutoGeneratedTcpMessage<PlayerState> {
        public static final byte id = 14;
    }

    public static abstract class EntityStateMessage extends AutoGeneratedTcpMessage<EntityState> {
        public static final byte id = 15;
    }

}
