package utils;

import static javax.lang.model.element.ElementKind.RECORD;
import static javax.lang.model.element.Modifier.FINAL;
import static javax.lang.model.element.Modifier.PRIVATE;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Types;

import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.TypeName;

public class GenericTypeUtils {
    public final static DeclaredType typeElementOutOfTypeMirror(TypeMirror typeMirror, Types typeUtils) {
        if (typeMirror.getKind() == TypeKind.DECLARED) {
            DeclaredType declaredType = (DeclaredType) typeMirror;
            return declaredType; // returns the TypeElement
        }

        throw new IllegalStateException("Primitive type or array encountered here");
    }

    public final static TypeMirror getTemplateArgTypeMirror(TypeMirror typeMirror, Types typeUtils) {
        var declared = typeElementOutOfTypeMirror(typeMirror, typeUtils);

        var typeArgs = declared.getTypeArguments();

        if (typeArgs.size() != 1) {
            throw new IllegalStateException();
        }

        return typeArgs.getFirst();
    }

    public final static TypeMirror getTemplateArgTypeMirror(TypeElement element) {
        var superClass = (DeclaredType) element.getSuperclass();
        var typeArgs = superClass.getTypeArguments();

        if (typeArgs.size() != 1) {
            throw new IllegalStateException();
        }

        return typeArgs.getFirst();
    }

    private final static TypeElement getGenericTypePar(TypeMirror typeMirror,
            ProcessingEnvironment processingEnvironment) {
        var typeUtils = processingEnvironment.getTypeUtils();
        var typeEl = (TypeElement) typeUtils.asElement(typeMirror);

        // processingEnvironment.getMessager().printNote("Record type:
        // %s".formatted(typeEl.toString()));
        return typeEl;
    }

    public final static Iterable<FieldSpec> getFieldSpecs(TypeMirror typeMirror,
            ProcessingEnvironment processingEnvironment) {
        var typeEl = getGenericTypePar(typeMirror, processingEnvironment);

        if (typeEl.getKind() != RECORD) {
            processingEnvironment.getMessager().printError(
                    "Template argument: %s to AutoGeneratedMessage should be a record".formatted(typeEl));
            throw new IllegalStateException();
        }

        var recordFields = typeEl.getRecordComponents();

        return recordFields.stream().map(recordComponent -> FieldSpec.builder(TypeName.get(recordComponent.asType()),
                recordComponent.getSimpleName().toString(), PRIVATE, FINAL)
                .build()).toList();
    }
}
