package utils;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;

import org.junit.jupiter.api.Test;

public class FixedSizeArrayWrapperTest {
    private FixedSizeArrayWrapper<Integer> arrayWrapper;

    private static Collection<Integer> createAListOfAGivenSize(final int size) {
        final var list = new LinkedList<Integer>();

        for (int i = 0; i < size; i++) {
            list.add(i);
        }

        return list;
    }

    @Test
    void arrayThatIsTooBigShouldntBeAllowed() {
        final var list = createAListOfAGivenSize(FixedSizeArrayWrapper.maxSize + 1);

        assertThrows(AssertionError.class, () -> {
            arrayWrapper = new FixedSizeArrayWrapper<>(list, Integer.class);
        });
    }

    @Test
    void arrayThatHasSizeEqualToMaxsizeShouldBeAllowed() {
        final var list = createAListOfAGivenSize(FixedSizeArrayWrapper.maxSize);

        assertDoesNotThrow(() -> {
            arrayWrapper = new FixedSizeArrayWrapper<>(list, Integer.class);
        });
    }

    @Test
    void testWhetherTheContentsAreActuallyPresentInTheWrappedArray() {
        var list = createAListOfAGivenSize(FixedSizeArrayWrapper.maxSize);

        arrayWrapper = new FixedSizeArrayWrapper<>(list, Integer.class);

        assertArrayEquals(list.toArray(), arrayWrapper.getData());
    }

    @Test
    void testConstructorWithCollectionAndClass() {
        List<String> list = Arrays.asList("x", "y", "z");
        FixedSizeArrayWrapper<String> wrapper = new FixedSizeArrayWrapper<>(list, String.class);
        assertNotNull(wrapper);
        assertArrayEquals(list.toArray(new String[0]), wrapper.getData(), "Array contents should match collection");
    }

    @Test
    void testConstructorWithEmptyCollection() {
        List<Integer> emptyList = Collections.emptyList();
        FixedSizeArrayWrapper<Integer> wrapper = new FixedSizeArrayWrapper<>(emptyList, Integer.class);
        assertNotNull(wrapper);
        assertEquals(0, wrapper.getData().length, "Array should be empty");
    }

    @Test
    void testGetArrayFromSupplierGeneratesCorrectArray() {
        Supplier<Integer> supplier = () -> 7;
        FixedSizeArrayWrapper<Integer> wrapper = FixedSizeArrayWrapper.getArrayFromSupplier((byte) 5, supplier,
                Integer.class);

        assertNotNull(wrapper);
        assertEquals(5, wrapper.getData().length, "Array should have length 5");
        for (int val : wrapper.getData()) {
            assertEquals(7, val, "All elements should be generated by supplier");
        }
    }

    @Test
    void testGetArrayFromSupplierWithZeroLength() {
        Supplier<String> supplier = () -> "hello";
        FixedSizeArrayWrapper<String> wrapper = FixedSizeArrayWrapper.getArrayFromSupplier((byte) 0, supplier,
                String.class);
        assertNotNull(wrapper);
        assertEquals(0, wrapper.getData().length, "Array length should be zero");
    }

    @Test
    void testForEachConsumesAllElements() {
        List<Integer> list = Arrays.asList(1, 2, 3, 4);
        FixedSizeArrayWrapper<Integer> wrapper = new FixedSizeArrayWrapper<>(list, Integer.class);

        AtomicInteger sum = new AtomicInteger(0);
        wrapper.forEach(sum::addAndGet);

        assertEquals(10, sum.get(), "forEach should apply consumer to all elements");
    }

    @Test
    void testForEachWithEmptyArray() {
        FixedSizeArrayWrapper<String> wrapper = new FixedSizeArrayWrapper<>(Collections.emptyList(), String.class);
        AtomicInteger counter = new AtomicInteger(0);

        wrapper.forEach(s -> counter.incrementAndGet());

        assertEquals(0, counter.get(), "forEach on empty array should not call consumer");
    }

    @Test
    void testGetArrayFromSupplier() {
        // given
        byte len = 5;
        Supplier<String> supplier = () -> "x";

        // when
        var wrapper = FixedSizeArrayWrapper.getArrayFromSupplier(len, supplier, String.class);

        // then
        AtomicInteger counter = new AtomicInteger(0);
        wrapper.forEach(s -> {
            assertEquals("x", s);
            counter.incrementAndGet();
        });
        assertEquals(len, counter.get());
    }

    @Test
    void testForEach() {
        var wrapper = FixedSizeArrayWrapper.getArrayFromSupplier((byte) 3, () -> 42, Integer.class);

        AtomicInteger sum = new AtomicInteger();
        wrapper.forEach(sum::addAndGet);

        assertEquals(42 * 3, sum.get());
    }

    @Test
    void testAccumulate() {
        var wrapper = FixedSizeArrayWrapper.getArrayFromSupplier((byte) 4, () -> 2, Integer.class);

        Integer sum = wrapper.accumulate(0, Integer::sum);

        assertEquals(8, sum); // 4 elements * 2
    }
}
