package network.messages.decoding;

import java.io.IOException;
import java.util.Optional;
import java.util.logging.Logger;

import network.messages.loginstate.LogInQuery;
import network.messages.loginstate.LogInResponse;
import network.messages.utils.DataProducer;
import network.messages.Message;
import network.messages.defaultmessage.AutoGeneratedMessages;
import java.util.function.Function;
import java.util.HashMap;
import java.util.Map;

public class ConcreteMessageDecoder implements MessageDecoder {
    private static final Logger logger = Logger.getGlobal();

    private static final Map<Byte, Function<DataProducer, ? extends Message>> decoders = new HashMap<>();
    static {
        decoders.putAll(AutoGeneratedMessages.decoders);
    }

    // private static final Map<Byte, Function<Object, Message>> recordDecoders =
    // new HashMap<>();

    @Override
    public Message decodeMessage(DataProducer dataProducer) throws IOException {
        byte messageCode = dataProducer.getByte();

        logger.finer(String.format("Received message of code: %s", messageCode));

        switch (messageCode) {
            case LogInQuery.id -> {
                var username = dataProducer.getString();
                var password = dataProducer.getString();
                return new LogInQuery(username, password);
            }

            case LogInResponse.id -> {
                int answer = dataProducer.getInt();
                return new LogInResponse(
                        (answer == LogInResponse.NO_AUTH_TOKEN) ? Optional.empty() : Optional.of(answer),
                        dataProducer.getInt());
            }

            default -> {
                return decoders.get(messageCode).apply(dataProducer);
            }
        }
    }
}
