plugins {
    id 'java-library'
    id 'application'
}

dependencies {
    implementation project(':client')
    //TODO: maybe remove this. This should not be needed
    implementation project(':core')

    api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"

    api "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
}

application {
  mainClass = 'DesktopLauncher'
}

tasks.register("dummylauncher", JavaExec) {
    group = 'Mocking the game'
    description = 'Running the game with no server connection or configuration phase'

    // group = ApplicationPlugin.APPLICATION_GROUP
    classpath = sourceSets.main.runtimeClasspath

    mainClass = 'dummylaunchers.DummyGameLauncher'
}

run {
    if (org.gradle.internal.os.OperatingSystem.current().isMacOsX()) {
        jvmArgs += "-XstartOnFirstThread"
    }
}
